### ISSUE TITLE
Refactor last modified date to be rendered client side

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-helpx#8]
The last modified date is currently rendered "server" side and uses "difference" time ("Last modified xxx months ago"). Since the html is cache, the difference is wrong: it is the difference at the time of the caching and not at client rendering time.

Fixing that "issue" will allow to introduce some JS client side code and give more consistence to the project.

**Comment by davidnuescheler** [comment]
so i think that would mean that we would inline the actual last mod date and have a little javascript decoration that turns that into human readable (aka. 3 minutes ago), right?

**Comment by trieloff** [comment]
Yes, that's the idea. Something that looks like this in the HTML: `<span class="date" data-timestamp="1223782721">October 1st 1985, 5:23 pm</span>` and then a small library that gets all `date`-classed elements and replaces their value.

**Comment by kptdobe** [comment]
Yes. 
I'd like to use this opportunity to create a web project, have a dependency to moment.js... just to see what is needed.

**Comment by davidnuescheler** [comment]
@trieloff i don't think you need the timestamp, so think the html would look something like this:

```html
<span class="date">Thu Jun 21 2018 10:24:44 GMT-0700 (Pacific Daylight Time)</span>
```

**Comment by tripodsan** [comment]
I prefer @trieloff version, but I would try to follow microformat patterns:

```
<time datetime="2018-10-24T12:24:44-0700">
  Thu Jun 21 2018 10:24:44 GMT-0700
</time>
```

or

```
<span class="helpx-date" datetime="2018-10-24T12:24:44-0700">
  Thu Jun 21 2018 10:24:44 GMT-0700
</span>
```

**Comment by kptdobe** [comment]
Just merged a simple client side implementation.
